#! /bin/bash
# This is voting
# Sam Kvale Feb. 2015

if grep -q $USER /var/www/html/csclub/SECRETvoting/alreadyVoted.txt; then
    echo "ERROR!!  you have already voted"
    exit 0
fi
echo "Hello $USER"
echo "Although this file knows you are $USER, it does not keep a record of who you vote for, just that you have voted."
echo "Here are the rules: 
  
  1) The person with the most votes after the voting process will get the position.
  2) You can only vote once.  This is a one shot deal. Vote for all of the positions here and know that you will be excluded from voting in the future.
  3) At any time before the end you may cancel all of your votes and quit with Control C.
  4) If you want to nominate a different person, make sure you go through the form online at cs.bemidjistate.edu/cslcub
  5) Choose choice 0 to write your own choice in.
"
voteArray=""
declare -a arr=('[^-]president' 'vice-president' 'treasurer' 'secretary')
for i in "${arr[@]}"
do
    echo "
    Your options for $i are " | sed 's/\[^-\]//' 
    var=`egrep -i $i /var/www/html/csclub/SECRETvoting/nominations.txt | nl -b a`
    echo -e "${var}"
    echo -n "Vote for a person above (Choose the number next to their name) : "
    read x
    lines=`echo -e "${var}" | wc -l`
    numbers='^[0-9]+$'
    if ! [[ $x =~ $numbers ]] ; then
       echo "error: $x is NOT a number" >&2; exit 1
    fi
    if [ $x -gt $lines ]; then
        echo "$x was not a choice.  From the top!";
        exit 1
    fi
    if [ $x -lt 0 ]; then
        echo "$x was less than 0..."
        exit 1
    fi
    if [ $x -eq 0 ]; then
        echo -n "Who do you want to vote for? "
        read voted
    else
        voted=`egrep -i $i /var/www/html/csclub/SECRETvoting/nominations.txt | nl -b a | grep $x | awk '{print $2 , $3}'`
    fi
    echo -n "Are you sure you want to vote for $voted as $i? (Y/N)  " | sed 's/\[^-\]//'
    read ans
    if [[ $ans =~ [Yy] ]]; then
        voteArray=`echo "$voteArray\n$voted $i" | sed 's/\[^-\]//' `
    else
        echo "Okay let's try it from the top"
        exit 2
    fi
done
echo ""
echo -e "${voteArray}"
echo ""
echo -n "We are almost done.  Are you sure you voted for all of the right people? [Y/N]"
read okay
echo ""
if [[ $okay =~ [Yy] ]]; then
    echo -e $voteArray >>  /var/www/html/csclub/SECRETvoting/votedFor.txt
    echo $USER >> /var/www/html/csclub/SECRETvoting/alreadyVoted.txt
    echo "Voting has been recorded and you have been denied access to voting again"
    exit 0
else
    echo "Okay nothing has been recorded.  From the top!"
    exit 1
fi
